# Adding fonts for your app is easy, just set them like this:
#
#   - name: "my-font-family-name"
#     src:  "my_font_file.otf"
#
# If the font file is stored in static/fonts, if font loading is from a composer package you set like this:
#
#   - name: "my-font-composer"
#     src:  "my_font_file.otf"
#     package: "font-vendor/vendor-pkg"
#
# Or if the font will be loaded from other URL:
#
#   - name: "my-font-from-the-web"
#     src:  "//mycdn.myhost.com/fonts/myfont.otf"
#     remote: true
#
# Thats it :)