# Adding javascript files for your app is easy, just set them like this:
#
#   - src: "myjsfile"
#
# If the font file is stored in static/javascript, if your javascript must be processed by php (aka Tagged Files) you
# must add the dynamic: true option, like this:
#
#   - src: "myjsfile"
#     dynamic: true
#
# If the file is stored in a composer package you should add it like this:
#
#   - src:  "path/to/the/js/file"
#     package: "js-vendor/vendor-pkg"
#
# Or if the file will be loaded from an external URL:
#
#   - src:  "//mycdn.myhost.com/js/myjs.js"
#     remote: true
#
# Only when loading from remote you must write ".js" at the end (containing file extension),
# also remember dynamic javascript (processed by PHP) can only be loaded from the static/javascript folder
# js files from a composer package and remote javascript are not allowed.
#
# Thats it :)