<form class="form-horizontal">
    <fieldset>
        <!-- Form Name -->
        <legend>Nuevo Artículo</legend>
        <!-- Text input-->
        <div class="form-group">
            <label class="col-md-3 control-label" for="titulo">Título</label>
            <div class="col-md-6">
                <input id="titulo" name="titulo" type="text" placeholder="placeholder" class="form-control ">
                <p class="help-block">help</p>
            </div>
        </div>

        <!-- Textarea -->
        <div class="form-group">
            <label class="col-md-3 control-label" for="texto">Texto</label>
            <div class="col-md-6">
                <textarea id="texto" name="texto" class="form-control ">default text</textarea>
            </div>
        </div>

        <!-- Button -->
        <div class="form-group">
            <label class="col-md-3 control-label" for=""></label>
            <div class="col-lg-6">
                <button id="" name="" class="btn btn-primary">Guardar Artículo</button>
            </div>
        </div>

    </fieldset>
</form>