<!doctype html>
<html lang="en">
<head>

	<meta charset="UTF-8">
	<title>MVC-ExEngine Default Layout</title>
<?=$LayoutAssets->CSS?>
<?=$LayoutAssets->JS?>

<?=$LayoutAssets->Fonts?>
</head>
<body>

<?=$Content?>

</body>
</html>
<!--
	This is an example layout, you can change this or create a new one, if you want to set a different layout as default, set at the `config/eemvc.php` file in the ApplicationInit method,
	also you can set the layout at runtime in any controller action using `$this->layout = 'my_layout_file'`, remember to set the Content placeholder and the assets placeholders ($LayoutAssets->CSS, JS and Fonts) 
	in your layouts for best performing	MVC-ExEngine.
	
	QOX Corporation - www.qox-corp.com
-->